apiVersion: cli.kyverno.io/v1alpha1
kind: Test
metadata:
  name: kyverno-test.yaml
policies:
- ../require-resource-quota.yaml
resources:
- resource.yaml
results:
- kind: Namespace
  policy: require-resource-quota
  resources:
  - ns-resource-quota
  result: pass
  rule: resourcequotas
variables: values.yaml
