apiVersion: v1
kind: Namespace
metadata:
  name: ns-resource-quota
spec: {}

---

apiVersion: v1
kind: ResourceQuota
metadata:
  name: foo-resource-quota
  namespace: ns-resource-quota
spec:
  hard:
    cpu: "1000"
    memory: 200Gi
    pods: "10"
  scopeSelector:
    matchExpressions:
    - operator : In
      scopeName: PriorityClass
      values: ["high"]
